### ISSUE TITLE
Why React-Helmet?

### ISSUE THREAD

**Issue by Fazliddin-04** [bradtraversy/house-marketplace#1]
Hello Mr. Traversy! I learned your "React: Front to Back 2022" course with excitement. That's cool. I want to ask that, you didn't use 'react-helmet' in this project, but in the [Listing](https://github.com/bradtraversy/house-marketplace/blob/main/src/pages/Listing.jsx) page, Helmet was put. If there is no helmet, the project is still working as well as before. Why do we need the helmet here?

**Comment by bushblade** [comment]
Hi @Fazliddin-04 react-helmet is used in this project.
You can see it listed in [package.json here](https://github.com/bradtraversy/house-marketplace/blob/2cb8d6fd59818059762b24d3f72441f218a9d245/package.json#L13)
