### ISSUE TITLE
getFirestore() missing app parameter

### ISSUE THREAD

**Issue by matthosch** [bradtraversy/house-marketplace#3]
Comparing our initialization of the firestore db, we do not pass app to the getFirestore function as in the example from https://firebase.google.com/docs/web/setup.
https://github.com/bradtraversy/house-marketplace/blob/2cb8d6fd59818059762b24d3f72441f218a9d245/src/firebase.config.js#L16

```
import { initializeApp } from 'firebase/app';
import { getFirestore, collection, getDocs } from 'firebase/firestore/lite';
// Follow this pattern to import other Firebase services
// import { } from 'firebase/<service>';

// TODO: Replace the following with your app's [Firebase project configuration](https://firebase.google.com/docs/web/learn-more#config-object)
const firebaseConfig = {
  //...
};

const app = initializeApp(firebaseConfig);
const db = getFirestore(app);

// Get a list of cities from your database
async function getCities(db) {
  const citiesCol = collection(db, 'cities');
  const citySnapshot = await getDocs(citiesCol);
  const cityList = citySnapshot.docs.map(doc => doc.data());
  return cityList;
}
```
Just trying to understand when it is and isn't required. FirestoreClient reference [here](https://firebase.google.com/docs/reference/admin/java/reference/com/google/firebase/cloud/FirestoreClient#public-methods).

**Comment by bushblade** [comment]
Hi @matthosch 
You're checking the Java docs there.
You need to check the [JavaScript documentation.](https://firebase.google.com/docs/reference/js/firestore_.md#getfirestore)
*app* is optional, if you don't provide an argument you get the Firestore associated with your app from calling `initalizeApp`
You can also check the function signature in your editor....
![Screenshot_2022-03-11_22-27-36](https://user-images.githubusercontent.com/21976188/157981966-8cabce7b-c917-4b0e-8334-1803caf3e175.png)

That's in Neovim but VS Code uses the same TypeScript language server so should show the same documentation.
